# Doctrine Configuration
doctrine:
  orm:
    resolve_target_entities:
      Ibrows\SyliusShopBundle\Model\Address\DeliveryAddressInterface: %ibrows_sylius_shop.deliveryaddress.class%
      Ibrows\SyliusShopBundle\Model\Address\InvoiceAddressInterface: %ibrows_sylius_shop.invoiceaddress.class%

      Ibrows\SyliusShopBundle\Model\Product\ProductInterface: %ibrows_sylius_shop.product.class%

      Ibrows\SyliusShopBundle\Model\CartInterface: %ibrows_sylius_shop.cart.class%
      Ibrows\SyliusShopBundle\Model\CartItemInterface: %ibrows_sylius_shop.cartitem.class%
      Ibrows\SyliusShopBundle\Model\AdditionalCartItemInterface: %ibrows_sylius_shop.additionalcartitem.class%