# Doctrine Configuration
doctrine:
  orm:
    resolve_target_entities:
      Ibrows\SyliusShopBundle\Model\Address\DeliveryAddressInterface: %ibrows_sylius_shop.deliveryaddress.class%
      Ibrows\SyliusShopBundle\Model\Address\InvoiceAddressInterface: %ibrows_sylius_shop.invoiceaddress.class%

      Ibrows\SyliusShopBundle\Model\Delivery\DeliveryOptionInterface: Ibrows\SyliusShopBundle\Entity\AdditionalCartItem
      Ibrows\SyliusShopBundle\Model\Payment\PaymentOptionsInterface: %ibrows_sylius_shop.paymentoptions.class%

      Ibrows\SyliusShopBundle\Model\Product\ProductInterface: %ibrows_sylius_shop.product.class%
      
      JMS\Payment\CoreBundle\Model\PaymentInstructionInterface: JMS\Payment\CoreBundle\Entity\PaymentInstruction